"""Add_operating_hours

Revision ID: 445b0a8324a1
Revises: 1a4f5df0338f
Create Date: 2026-05-31 16:25:00.054582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '445b0a8324a1'
down_revision: Union[str, Sequence[str], None] = '1a4f5df0338f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('umkm', sa.Column('operating_hours', sa.JSON(), nullable=True))
    op.drop_column('umkm', 'is_open')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('umkm', sa.Column('is_open', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('umkm', 'operating_hours')
    # ### end Alembic commands ###
