"""empty message

Revision ID: 549e58010f02
Revises: 5c09a2c44614
Create Date: 2026-05-16 19:15:26.290503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '549e58010f02'
down_revision: Union[str, Sequence[str], None] = '5c09a2c44614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('reviews_order_id_key'), 'reviews', type_='unique')
    op.create_unique_constraint('unique_review_per_order_item', 'reviews', ['order_id', 'menu_item_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_review_per_order_item', 'reviews', type_='unique')
    op.create_unique_constraint(op.f('reviews_order_id_key'), 'reviews', ['order_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
