"""add photo_url to promotions

Revision ID: 5c09a2c44614
Revises: 068f867e7ae1
Create Date: 2026-05-01 17:37:51.920134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c09a2c44614'
down_revision: Union[str, Sequence[str], None] = '068f867e7ae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promotions', sa.Column('photo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promotions', 'photo_url')
    # ### end Alembic commands ###
