"""update_category_enum_and_notes

Revision ID: 781a084657e9
Revises: 29ace9add13a
Create Date: 2026-04-23 14:15:19.747998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '781a084657e9'
down_revision: Union[str, Sequence[str], None] = '29ace9add13a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1. Buat tipe ENUM di database
    productcategory_enum = postgresql.ENUM('MAKANAN', 'MINUMAN', 'JAJANAN', name='productcategory')
    productcategory_enum.create(op.get_bind())

    # 2. TAMBAHKAN BARIS INI: Ubah semua data lama menjadi 'MAKANAN' agar sesuai dengan ENUM
    op.execute("UPDATE menu_items SET category = 'MAKANAN'")

    # 3. Ubah tipe kolomnya
    op.alter_column('menu_items', 'category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('MAKANAN', 'MINUMAN', 'JAJANAN', name='productcategory'),
               postgresql_using="category::productcategory",
               nullable=False)
    op.drop_index(op.f('ix_menu_items_category'), table_name='menu_items')
    op.add_column('order_items', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'notes')
    op.create_index(op.f('ix_menu_items_category'), 'menu_items', ['category'], unique=False)
    op.alter_column('menu_items', 'category',
               existing_type=sa.Enum('MAKANAN', 'MINUMAN', 'JAJANAN', name='productcategory'),
               type_=sa.VARCHAR(length=50),
               nullable=False)
    
    productcategory_enum = postgresql.ENUM('MAKANAN', 'MINUMAN', 'JAJANAN', name='productcategory')
    productcategory_enum.drop(op.get_bind())
    # ### end Alembic commands ###
