"""empty message

Revision ID: ac1afbf44583
Revises: 549e58010f02
Create Date: 2026-05-18 15:32:14.991473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac1afbf44583'
down_revision: Union[str, Sequence[str], None] = '549e58010f02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'menu_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.add_column('orders', sa.Column('payment_method', sa.String(length=50), nullable=False))
    op.add_column('orders', sa.Column('payment_proof_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_proof_url')
    op.drop_column('orders', 'payment_method')
    op.alter_column('order_items', 'menu_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
