"""create_reviews_table

Revision ID: d8f2c335ee80
Revises: 43dde2555e78
Create Date: 2026-04-29 15:45:51.564502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8f2c335ee80'
down_revision: Union[str, Sequence[str], None] = '43dde2555e78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('reviews_buyer_id_fkey'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('reviews_order_id_fkey'), 'reviews', type_='foreignkey')
    op.drop_constraint(op.f('reviews_menu_item_id_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'users', ['buyer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reviews', 'menu_items', ['menu_item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'reviews', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # Kita skip langkah ini, biarkan file migrasi pertama yang menghapus tabelnya
    pass